### ISSUE TITLE
Changes from Cartographic Review

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/wetland-projects-v2#28]
- [x] Add the text below  to the About tab text after the Recent Projects section:
 > The Image Year layer identifies the decade of imagery that was used to collect the wetlands data that is currently posted on the Wetlands Mapper.
- [x] Link the headings (recent, active, image year) to the about tab. Remove the '?' link from 'Image Year' in the layers side bar (optional: add '?' to all layers and also link them to the about tab)

Do below and send to Mitch for review
- [x] Most people will not use the imagery base map, but.....try adding a white fill to the hatch pattern with high transparency..75-85% and see what that looks like on imagery.

- [x] Also consider making the 'About' link a little lighter.   It is almost too subtle on the header bar.   Not much lighter but a bit.

**Comment by kjacobsen16** [comment]
Doesn't look like it's possible to set the transparency for only the white fill in the active layer, unless we use multiple layers, which gets messy in the code.  We can add a white fill, just can't set a separate transparency for that.  Since Mitch thinks it's not likely people will use the imagery basemaps, we can disregard this change and leave as is, or we can add a white fill, and the user can play around with the transparency for the Active layer themselves.. ?
